import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { RootState } from "./store";
import { useSelector, useDispatch } from "react-redux";
import {
  countValue,
  decrease,
  decrement,
  increase,
  increment,
} from "./slice/counterSlice";
import { selectValue } from "./slice/counterSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const count = useSelector(selectValue);
  const basketCount = useSelector(countValue);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>value of the count is : {count}</h1>
        <button
          onClick={() => dispatch(increment())}
          style={{
            margin: "20px",
            height: "30px",
            width: "100px",
            cursor: "pointer",
          }}
        >
          increment
        </button>

        <button
          onClick={() => dispatch(decrement())}
          style={{
            margin: "20px",
            height: "30px",
            width: "100px",
            cursor: "pointer",
          }}
        >
          decrement
        </button>
        <hr />

        <button
          onClick={() => dispatch(increase())}
          style={{
            margin: "20px",
            height: "30px",
            width: "100px",
            cursor: "pointer",
          }}
        >
          Increase
        </button>
        <h2>Basket value: {basketCount}</h2>
        {basketCount >=1 ?

          <button
            onClick={() => dispatch(decrease())}
            style={{
              margin: "20px",
              height: "30px",
              width: "100px",
              
              cursor: "pointer",
            }}
            >
            Decrease
          </button>
          :""
        }
      </div>
    </>
  );
}
